### ISSUE TITLE
subprocess.CalledProcessError: Command '['/home/xxx/bin/python3', '-u', 'tools/test.py', '--local_rank=0', 'configs/imvoxelnet/imvoxelnet_kitti.py', 'work_dirs/20210503_214214.pth', '--launcher', 'pytorch', '--eval', 'mAP']' returned non-zero exit status 1.`

### ISSUE THREAD

**Issue by Light--** [saic-vul/imvoxelnet#43]
run
```
$ bash tools/dist_test.sh configs/imvoxelnet/imvoxelnet_kitti.py work_dirs/20210503_214214.pth 1 --eval mAP
```

and report:
```
Traceback (most recent call last):
  File "tools/test.py", line 9, in <module>
    from mmdet3d.apis import single_gpu_test
  File "/home/xxx/imvoxelnet-master/mmdet3d/apis/__init__.py", line 1, in <module>
    from .inference import inference_detector, init_detector, show_result_meshlab
  File "/home/xxx/imvoxelnet-master/mmdet3d/apis/inference.py", line 8, in <module>
    from mmdet3d.core import Box3DMode, show_result
  File "/home/xxx/imvoxelnet-master/mmdet3d/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/xxx/imvoxelnet-master/mmdet3d/core/bbox/__init__.py", line 4, in <module>
    from .iou_calculators import (AxisAlignedBboxOverlaps3D, BboxOverlaps3D,
  File "/home/xxx/imvoxelnet-master/mmdet3d/core/bbox/iou_calculators/__init__.py", line 1, in <module>
    from .iou3d_calculator import (AxisAlignedBboxOverlaps3D, BboxOverlaps3D,
  File "/home/xxx/imvoxelnet-master/mmdet3d/core/bbox/iou_calculators/iou3d_calculator.py", line 5, in <module>
    from ..structures import get_box_type
  File "/home/xxx/imvoxelnet-master/mmdet3d/core/bbox/structures/__init__.py", line 1, in <module>
    from .base_box3d import BaseInstance3DBoxes
  File "/home/xxx/imvoxelnet-master/mmdet3d/core/bbox/structures/base_box3d.py", line 5, in <module>
    from mmdet3d.ops.iou3d import iou3d_cuda
  File "/home/xxx/imvoxelnet-master/mmdet3d/ops/__init__.py", line 5, in <module>
    from .ball_query import ball_query
  File "/home/xxx/imvoxelnet-master/mmdet3d/ops/ball_query/__init__.py", line 1, in <module>
    from .ball_query import ball_query
  File "/home/xxx/imvoxelnet-master/mmdet3d/ops/ball_query/ball_query.py", line 4, in <module>
    from . import ball_query_ext
ImportError: cannot import name 'ball_query_ext' from 'mmdet3d.ops.ball_query' (/home/xxx/imvoxelnet-master/mmdet3d/ops/ball_query/__init__.py)
Traceback (most recent call last):
  File "/home/xxx/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xxx/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xxx/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/xxx/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/xxx/bin/python3', '-u', 'tools/test.py', '--local_rank=0', 'configs/imvoxelnet/imvoxelnet_kitti.py', 'work_dirs/20210503_214214.pth', '--launcher', 'pytorch', '--eval', 'mAP']' returned non-zero exit status 1.
```

**Comment by filaPro** [comment]
Hi @Light-- ,

It is the problem with installing of `cuda` modules of `mmdetection3d`. Have you run `pip install .` like [here](https://github.com/saic-vul/imvoxelnet/blob/master/docker/Dockerfile#L24)? You need to get something like `ball_query_ext.cpython-37m-x86_64-linux-gnu.so` in `mmdet3d/ops/ball_query`.

**Comment by Light--** [comment]
@filaPro thank you for reply.
i already done what you said. i followed the install process in dockerfile, but only got error like above
i tried many times but failed. i dont know why.
could you give me minimal example to fix this problem?
looking forward to your reply. thanks again

**Comment by filaPro** [comment]
So, can you check if `ball_query_ext.cpython-37m-x86_64-linux-gnu.so` actually exists in `mmdet3d/ops/ball_query` after your installation process?

**Comment by Light--** [comment]
> So, can you check if `ball_query_ext.cpython-37m-x86_64-linux-gnu.so` actually exists in `mmdet3d/ops/ball_query` after your installation process?

no, sorry i can't found that file. i checked that and it doesn't exist there.

> You can also check same issues in original `mmdetection3d` [repo](https://github.com/open-mmlab/mmdetection3d/issues?q=cannot+import+name+%27ball_query_ext%27).

yes, i have searched issues before, but didn't find a solution...

could u please help me to figure it out?
thank you!

**Comment by Light--** [comment]
> This means that installation actually fails. Have you checked your `cuda` during installation? Like `torch.cuda.is_avaliable()`.

yes, cuda is available.


> Also have you tried to build our `Dockerfile`? It helps in several issues here [1](https://github.com/saic-vul/imvoxelnet/issues/16#issuecomment-874918229), [2](https://github.com/saic-vul/imvoxelnet/issues/24#issuecomment-906234597).

my question is how can i use it without docker，like install all the libs from scratch.  if can use docker, i would not try this way.

thx
