### ISSUE TITLE
 python tools/create_data.py nuscenes error

### ISSUE THREAD

**Issue by Bincle-Yin** [saic-vul/imvoxelnet#44]
Hi,When i run creat_data.py --..... a error occurred:

```python
Traceback (most recent call last):
python tools/create_data.py nuscenes --root-path /media/hy/DISK1/data/nuscenes/mini/v1.0-mini --out-dir ./data/nuscenes --extra-tag nuscenes

  File "tools/create_data.py", line 5, in <module>
    from tools.data_converter import kitti_converter as kitti
  File "/home/hy/hy3d/imvoxelnet/tools/data_converter/kitti_converter.py", line 5, in <module>
    from mmdet3d.core.bbox import box_np_ops
  File "/home/hy/hy3d/imvoxelnet/mmdet3d/__init__.py", line 3, in <module>
    import mmdet
  File "/home/hy/anaconda3/envs/imvoxelnet/lib/python3.7/site-packages/mmdet/__init__.py", line 26, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.3.0 is used but incompatible. Please install mmcv>=1.3.17, <=1.5.0.
```
so, i updated mmcv version
```python
python tools/create_data.py nuscenes --root-path /media/hy/DISK1/data/nuscenes/mini/v1.0-mini --out-dir ./data/nuscenes --extra-tag nuscenes


Traceback (most recent call last):
  File "tools/create_data.py", line 5, in <module>
    from tools.data_converter import kitti_converter as kitti
  File "/home/hy/hy3d/imvoxelnet/tools/data_converter/kitti_converter.py", line 5, in <module>
    from mmdet3d.core.bbox import box_np_ops
  File "/home/hy/hy3d/imvoxelnet/mmdet3d/__init__.py", line 26, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.4.0 is used but incompatible. Please install mmcv>=1.1.5, <=1.3.0.

```
So what exactly is the MMCV version ==？

looking forward to y reply！

**Comment by filaPro** [comment]
Hi @Bincle-Yin ,

Have you tried with our [Dockerfile](https://github.com/saic-vul/imvoxelnet/blob/master/docker/Dockerfile) including `mmcv-full==1.2.7` and `mmdet==2.10.0`?

**Comment by Bincle-Yin** [comment]
Thank you very much for your reply,i resolve the problem .beacuse i used mmdetection  latest,so
```python
 git clone mmdetection version ==2.11.0 
 cd mmdetection/
 pip install -v -e .
```
but,  I met new problems
```python
(imvoxelnet) hy@hy-All-Series:~/hy3d/imvoxelnet$ python tools/create_data.py nuscenes --root-path /media/hy/DISK1/data/nuscenes/mini/v1.0-mini --out-dir ./data/nuscenes --extra-tag nuscenes
Traceback (most recent call last):
  File "tools/create_data.py", line 7, in <module>
    from tools.data_converter import nuscenes_converter as nuscenes_converter
  File "/home/hy/hy3d/imvoxelnet/tools/data_converter/nuscenes_converter.py", line 12, in <module>
    from mmdet3d.datasets import NuScenesDataset
  File "/home/hy/hy3d/imvoxelnet/mmdet3d/datasets/__init__.py", line 3, in <module>
    from .custom_3d import Custom3DDataset
  File "/home/hy/hy3d/imvoxelnet/mmdet3d/datasets/custom_3d.py", line 8, in <module>
    from ..core.bbox import get_box_type
  File "/home/hy/hy3d/imvoxelnet/mmdet3d/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/hy/hy3d/imvoxelnet/mmdet3d/core/bbox/__init__.py", line 4, in <module>
    from .iou_calculators import (AxisAlignedBboxOverlaps3D, BboxOverlaps3D,
  File "/home/hy/hy3d/imvoxelnet/mmdet3d/core/bbox/iou_calculators/__init__.py", line 1, in <module>
    from .iou3d_calculator import (AxisAlignedBboxOverlaps3D, BboxOverlaps3D,
  File "/home/hy/hy3d/imvoxelnet/mmdet3d/core/bbox/iou_calculators/iou3d_calculator.py", line 5, in <module>
    from ..structures import get_box_type
  File "/home/hy/hy3d/imvoxelnet/mmdet3d/core/bbox/structures/__init__.py", line 1, in <module>
    from .base_box3d import BaseInstance3DBoxes
  File "/home/hy/hy3d/imvoxelnet/mmdet3d/core/bbox/structures/base_box3d.py", line 5, in <module>
    from mmdet3d.ops.iou3d import iou3d_cuda
  File "/home/hy/hy3d/imvoxelnet/mmdet3d/ops/__init__.py", line 20, in <module>
    from .rotated_iou import IoU3DLoss, GIoU3DLoss
  File "/home/hy/hy3d/imvoxelnet/mmdet3d/ops/rotated_iou/__init__.py", line 1, in <module>
    from .iou3d_loss import IoU3DLoss, GIoU3DLoss
  File "/home/hy/hy3d/imvoxelnet/mmdet3d/ops/rotated_iou/iou3d_loss.py", line 7, in <module>
    from .oriented_iou_loss import cal_giou_3d, cal_iou_3d
  File "/home/hy/hy3d/imvoxelnet/mmdet3d/ops/rotated_iou/oriented_iou_loss.py", line 2, in <module>
    from .box_intersection_2d import oriented_box_intersection_2d
  File "/home/hy/hy3d/imvoxelnet/mmdet3d/ops/rotated_iou/box_intersection_2d.py", line 8, in <module>
    from .cuda_op.cuda_ext import sort_v
ModuleNotFoundError: No module named 'mmdet3d.ops.rotated_iou.cuda_op'
```
 now my conda env : 
pytorch==1.10.0 
mmcv                      1.3.0                   
mmcv-full                 1.3.0                    
mmdet                     2.11.0                
mmdet3d                   0.8.0                    
mmpycocotools             12.0.3 
cuda =10.2

**Comment by filaPro** [comment]
Did you follow `rotated_iou` instruction in installation section of our `readme`?

**Comment by Bincle-Yin** [comment]
> Did you follow `rotated_iou` instruction in installation section of our `readme`?

ohhh,thank y.
Follow the steps you I solved the problem.
this error was due to my carelessness.
